# Generated by Django 4.1.3 on 2022-12-02 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClinicData',
            new_name='ClinicalData',
        ),
    ]
